nohup python -u generate_response.py --index 0 > run_logs/0.log 2>&1 &
nohup python -u generate_response.py --index 1 > run_logs/1.log 2>&1 &
nohup python -u generate_response.py --index 2 > run_logs/2.log 2>&1 &
nohup python -u generate_response.py --index 3 > run_logs/3.log 2>&1 &
nohup python -u generate_response.py --index 4 > run_logs/4.log 2>&1 &
nohup python -u generate_response.py --index 5 > run_logs/5.log 2>&1 &
nohup python -u generate_response.py --index 6 > run_logs/6.log 2>&1 &
nohup python -u generate_response.py --index 7 > run_logs/7.log 2>&1 &
nohup python -u generate_response.py --index 8 > run_logs/8.log 2>&1 &
nohup python -u generate_response.py --index 9 > run_logs/9.log 2>&1 &
